import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { BookOpen, ChevronRight } from "lucide-react";

function MathBlock({ children }: { children: React.ReactNode }) {
  return (
    <div className="my-3 px-4 py-3 bg-secondary/60 border-l-2 border-primary rounded-r-md font-mono text-sm text-foreground/90 overflow-x-auto">
      {children}
    </div>
  );
}

function Section({ title, children, sub }: { title: string; children: React.ReactNode; sub?: string }) {
  const [open, setOpen] = useState(true);
  return (
    <div className="border border-border rounded-lg overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-5 py-4 bg-card hover:bg-secondary/40 transition-colors text-left"
      >
        <div>
          <div className="font-semibold">{title}</div>
          {sub && <div className="text-xs text-muted-foreground mt-0.5">{sub}</div>}
        </div>
        <ChevronRight size={14} className={`text-muted-foreground transition-transform ${open ? "rotate-90" : ""}`} />
      </button>
      {open && (
        <div className="px-5 py-4 bg-card/60 text-sm text-muted-foreground leading-relaxed space-y-3">
          {children}
        </div>
      )}
    </div>
  );
}

function Eq({ label, eq }: { label: string; eq: string }) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-2 items-start py-1">
      <div className="text-xs text-muted-foreground pt-1">{label}</div>
      <div className="md:col-span-2 font-mono text-sm bg-secondary/40 px-3 py-2 rounded border-l border-primary text-foreground/90">{eq}</div>
    </div>
  );
}

export default function Theory() {
  return (
    <div className="p-6 max-w-4xl mx-auto space-y-6">
      <div className="flex items-center gap-3 mb-6">
        <BookOpen size={20} style={{ color: "hsl(var(--primary))" }} />
        <div>
          <h1 className="text-xl font-bold">TK-FEM Theory</h1>
          <p className="text-sm text-muted-foreground">Trefftz-Koen Hybrid Finite Element Formulation — C.J. Koen (2026)</p>
        </div>
      </div>

      <Tabs defaultValue="overview">
        <TabsList className="flex-wrap h-auto gap-1">
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="governing">Governing Equations</TabsTrigger>
          <TabsTrigger value="transport">Koenian Transport</TabsTrigger>
          <TabsTrigger value="magnus">Magnus Expansion</TabsTrigger>
          <TabsTrigger value="assembly">Variational Assembly</TabsTrigger>
          <TabsTrigger value="kirsch">Kirsch Benchmark</TabsTrigger>
        </TabsList>

        {/* Overview */}
        <TabsContent value="overview" className="mt-5 space-y-4">
          <Card className="border-border bg-card">
            <CardHeader className="pb-2 pt-4">
              <CardTitle className="text-sm">Abstract</CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground leading-relaxed space-y-3">
              <p>
                This paper introduces a novel hybrid finite element formulation for linear elasticity that combines the classical <strong className="text-foreground">Trefftz philosophy</strong> of intra-element exact field satisfaction with a <strong className="text-foreground">Lie-series transport closure</strong> mechanism derived from Koenian Calculus.
              </p>
              <p>
                Unlike standard hybrid-Trefftz methods, which select intra-element fields from truncated T-complete families of known analytic solutions, the proposed <strong className="text-foreground">Trefftz-Koen (TK) method</strong> generates the local exact field by lifting the governing PDE to a first-order transport system and solving via a <strong className="text-foreground">Magnus expansion</strong> of a path-ordered exponential operator.
              </p>
              <p>
                When the Lie algebra generated by the elasticity operators satisfies closure conditions — <em>flatness, finite nilpotent class, and integrability</em> — the Magnus series terminates in finitely many terms, yielding an algebraically exact intra-element solution with <strong className="text-foreground">no interior interpolation or Gauss quadrature</strong>.
              </p>
            </CardContent>
          </Card>

          <div className="grid md:grid-cols-3 gap-4">
            {[
              {
                label: "Trefftz Philosophy",
                desc: "Intra-element field satisfies the governing PDE exactly in the strong sense — no weak equilibrium approximation.",
                color: "primary",
              },
              {
                label: "Koenian Calculus",
                desc: "One-shot closed-form solution via Lie-series transport. Replaces iterative guess-correct-iterate with a single continuous evaluation.",
                color: "accent",
              },
              {
                label: "Koenian Closure",
                desc: "When the Lie algebra is nilpotent of finite class m, the Magnus series truncates exactly — yielding a finite polynomial field.",
                color: "chart-3",
              },
            ].map(({ label, desc, color }) => (
              <Card key={label} className="border-border bg-card">
                <CardContent className="pt-4 pb-4">
                  <div className="font-semibold text-sm mb-2" style={{ color: `hsl(var(--${color}))` }}>{label}</div>
                  <div className="text-xs text-muted-foreground">{desc}</div>
                </CardContent>
              </Card>
            ))}
          </div>

          <Card className="border-border bg-card">
            <CardHeader className="pb-2 pt-4"><CardTitle className="text-sm">Method Comparison</CardTitle></CardHeader>
            <CardContent>
              <div className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="border-b border-border text-muted-foreground">
                      {["Feature", "Standard FEM", "HT-FEM", "TK-FEM"].map(h => (
                        <th key={h} className="text-left py-2 px-3 font-medium">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {[
                      ["Intra-element PDE", "Weak (approx)", "Exact (strong)", "Exact (strong)"],
                      ["Interior field source", "Polynomial interpolation", "Analytic T-complete basis", "Magnus/Lie transport"],
                      ["Basis selection", "Automatic (shape fns)", "Manual (analyst)", "Automatic (transport)"],
                      ["Gauss quadrature", "Required", "Boundary only", "None (closed case)"],
                      ["Stress accuracy", "1 order < disp", "Same as field", "Direct from gradient state"],
                      ["Element matrices", "Domain integrals", "Boundary integrals", "Boundary integrals"],
                      ["Heterogeneous mat.", "Easy", "Difficult", "Potentially easy"],
                      ["Nonlinear laws", "Iterative", "Very difficult", "Transport black-box"],
                    ].map(([feat, fem, ht, tk]) => (
                      <tr key={feat} className="border-b border-border/40">
                        <td className="py-2 px-3 font-medium text-foreground">{feat}</td>
                        <td className="py-2 px-3 text-muted-foreground">{fem}</td>
                        <td className="py-2 px-3 text-muted-foreground">{ht}</td>
                        <td className="py-2 px-3 text-primary font-medium">{tk}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Governing Equations */}
        <TabsContent value="governing" className="mt-5 space-y-4">
          <Section title="2D Linear Elasticity (Plane Stress)" sub="Strong-form PDE on domain Ω ⊂ ℝ²">
            <p>Consider a 2D elastic body on Ω with boundary ∂Ω = Γ_D ∪ Γ_N.</p>
            <div className="space-y-2 mt-3">
              <Eq label="Displacement field" eq="u(x,y) = [u_x(x,y), u_y(x,y)]ᵀ ∈ ℝ²" />
              <Eq label="Small-strain tensor" eq="ε(u) = ½(∇u + (∇u)ᵀ)" />
              <Eq label="Voigt notation" eq="[ε_xx, ε_yy, γ_xy]ᵀ = [∂u_x/∂x, ∂u_y/∂y, ∂u_x/∂y + ∂u_y/∂x]ᵀ" />
              <Eq label="Constitutive (plane stress)" eq="σ = (E/1-ν²) [[1,ν,0],[ν,1,0],[0,0,(1-ν)/2]] ε" />
              <Eq label="Equilibrium (strong form)" eq="∇·σ + f = 0  in Ω" />
              <Eq label="Boundary conditions" eq="u = ū on Γ_D,   σ·n = t̄ on Γ_N" />
            </div>
          </Section>

          <Section title="Classical FEM Limitations" sub="Why polynomial interpolation introduces error">
            <p>Standard displacement-based FEM:</p>
            <MathBlock>u_h(x,y) ≈ Σ N_i(x,y) d_i</MathBlock>
            <p>Key approximations that TK-FEM eliminates:</p>
            <ul className="list-disc pl-4 space-y-1">
              <li><strong className="text-foreground">Interpolation error:</strong> u_h does not satisfy ∇·σ = 0 inside elements</li>
              <li><strong className="text-foreground">Quadrature error:</strong> K_e = ∫ BᵀCB dA ≈ Σ w_g (BᵀCB)_g</li>
              <li><strong className="text-foreground">Stress patch problem:</strong> Stress accuracy is one order lower than displacement</li>
              <li><strong className="text-foreground">Mesh refinement:</strong> Required near stress concentrations</li>
            </ul>
          </Section>

          <Section title="Hybrid-Trefftz Philosophy" sub="What TK-FEM inherits and improves">
            <p>In Hybrid-Trefftz FEM, the intra-element field is constructed from a T-complete basis:</p>
            <MathBlock>u_h(x,y) = u^p(x,y) + Σ aₖ φₖ(x,y)   where ∇·C:∇φₖ = 0</MathBlock>
            <p>TK-FEM replaces the hand-built φₖ basis with Magnus-generated fields:</p>
            <MathBlock>u_h(x,y) = Π · exp(Ω(x,y)) · w₀   [Koenian transport field]</MathBlock>
            <p>The boundary frame û on ∂Ωe couples adjacent elements and provides the boundary state w₀.</p>
          </Section>
        </TabsContent>

        {/* Koenian Transport */}
        <TabsContent value="transport" className="mt-5 space-y-4">
          <Section title="The Koenian Transport Lift" sub="Recasting the 2nd-order PDE as a 1st-order transport system">
            <p>To apply Lie-series methods, the second-order elasticity PDE is lifted to a first-order system:</p>
            <p><strong className="text-foreground">Augmented state vector:</strong></p>
            <MathBlock>w(x,y) = [u_x, u_y, ∂_x u_x, ∂_x u_y, ∂_y u_x, ∂_y u_y]ᵀ ∈ ℝ⁶</MathBlock>
            <p><strong className="text-foreground">Transport system:</strong></p>
            <MathBlock>∂w/∂x = A_x w,   ∂w/∂y = A_y w</MathBlock>
            <p>For the current benchmark implementation, A_x and A_y are the flat commuting transport generators of the affine homogeneous-isotropic subspace.</p>
            <p>The broader Koenian geometry-connection operator family discussed in the paper remains a theory target rather than the current runtime implementation.</p>
            <MathBlock>{`A_x = [[0,0,1,0,0,0],
        [0,0,0,1,0,0],
        [0,0,0,0,0,0],
        [0,0,0,0,0,0],
        [0,0,0,0,0,0],
        [0,0,0,0,0,0]]`}</MathBlock>
            <MathBlock>{`A_y = [[0,0,0,0,1,0],
        [0,0,0,0,0,1],
        [0,0,0,0,0,0],
        [0,0,0,0,0,0],
        [0,0,0,0,0,0],
        [0,0,0,0,0,0]]`}</MathBlock>
            <p>For homogeneous isotropic elasticity these generators commute, so [A_x, A_y] = 0, the lower-central-series closure is abelian with m=1, and the benchmark Magnus generator reduces to the exact first-term exponential.</p>
          </Section>

          <Section title="Path-Parameterized Transport" sub="Along smooth paths γ(s) within an element">
            <p>Introduce a smooth path γ(s) = (x(s), y(s)) in element Ω_e, with γ(0) on ∂Ω_e and γ(1) at an interior point.</p>
            <p><strong className="text-foreground">Transport generator along γ:</strong></p>
            <MathBlock>G(s) = x'(s) A_x(x(s), y(s)) + y'(s) A_y(x(s), y(s))</MathBlock>
            <p>The transport equation becomes:</p>
            <MathBlock>dw/ds = G(s) w(s),   w(0) = w₀</MathBlock>
            <p>This is a first-order linear matrix ODE. The formal solution is the path-ordered exponential.</p>
          </Section>

          <Section title="Flatness Condition" sub="When the transport is path-independent">
            <p>For w(x,y) to be well-defined as a field (not path-dependent), the connection must be flat:</p>
            <MathBlock>R = dA − A ∧ A = ∂A_x/∂y − ∂A_y/∂x + [A_x, A_y] = 0</MathBlock>
            <p>For homogeneous isotropic elasticity, this condition is satisfied automatically (Schwarz theorem on mixed partials), confirming the system is integrable and the Magnus solution defines a valid field.</p>
          </Section>

          <Section title="Koenian Closure Conditions" sub="When the Magnus expansion terminates exactly">
            <p><strong className="text-foreground">Sufficient conditions for closure (nilpotent class m):</strong></p>
            <ol className="list-decimal pl-4 space-y-2">
              <li><strong className="text-foreground">Homogeneous, isotropic material:</strong> A_x, A_y are constant matrices. Commutator structure determines nilpotent class.</li>
              <li><strong className="text-foreground">Rectangular elements, straight paths:</strong> For paths γ(s) parallel to x or y, transport reduces to 1D with m=1.</li>
              <li><strong className="text-foreground">Symmetric/triangular Jacobian:</strong> If A = J_F dx is strictly upper-triangular, algebra is automatically flat (nilpotent class 1).</li>
            </ol>
            <p className="mt-2">When closure fails (curved elements, heterogeneous materials), the method reverts to a truncated Magnus approximation at order m_trunc — analogous to choosing a finite Trefftz basis, but generated automatically.</p>
          </Section>
        </TabsContent>

        {/* Magnus Expansion */}
        <TabsContent value="magnus" className="mt-5 space-y-4">
          <Section title="Magnus (1954) Expansion" sub="Exact exponential representation of the transport operator">
            <p>For the ODE dU/ds = A(s)U(s), U(0) = I, the formal solution is the path-ordered exponential U(s) = 𝒫exp(∫₀ˢ A dτ). If [A(s₁), A(s₂)] ≠ 0, the ordinary exponential exp(∫A) is incorrect. Magnus proved:</p>
            <MathBlock>U(s) = exp(Ω(s)),   Ω(s) = Σ Ωₖ(s)   (Magnus logarithm)</MathBlock>
            <p><strong className="text-foreground">First three Magnus terms:</strong></p>
            <MathBlock>Ω₁(s) = ∫₀ˢ A(τ) dτ</MathBlock>
            <MathBlock>Ω₂(s) = ½ ∫₀ˢ ∫₀^τ₁ [A(τ₁), A(τ₂)] dτ₂ dτ₁</MathBlock>
            <MathBlock>Ω₃(s) = ⅙ ∫₀ˢ ∫₀^τ₁ ∫₀^τ₂ ([A(τ₁),[A(τ₂),A(τ₃)]] + [A(τ₃),[A(τ₂),A(τ₁)]]) dτ₃ dτ₂ dτ₁</MathBlock>
            <p>where [A,B] = AB − BA is the matrix commutator.</p>
          </Section>

          <Section title="Nilpotent Truncation — Koenian Closure" sub="The key property that enables one-shot exact solutions">
            <p>If the Lie algebra generated by {"{A(τ) : τ ∈ [0,s]}"} is nilpotent of class m (all (m+1)-fold nested commutators vanish), then:</p>
            <MathBlock>{'Ω_{m+1}(s) = Ω_{m+2}(s) = ... = 0'}</MathBlock>
            <p>and the Magnus series becomes a finite sum:</p>
            <MathBlock>{'Ω(s) = Σk=1..m Ωk(s)   [finite!]'}</MathBlock>
            <p>This is the <strong className="text-foreground">closure property central to Koenian Calculus</strong>. For the current homogeneous isotropic benchmark transport used in the code, the closure class is m=1.</p>
          </Section>

          <Section title="Intra-Element Field Recovery" sub="Displacement, strain, and stress from the Magnus solution">
            <p><strong className="text-foreground">Displacement recovery via projection:</strong></p>
            <MathBlock>u(x,y) = Π w(x,y) = Π · exp(Ω(x,y)) · w₀</MathBlock>
            <p>where Π = [I₂ₓ₂, 0₂ₓ₄] extracts the first two components of the augmented state.</p>
            <p><strong className="text-foreground">Key properties of this field:</strong></p>
            <ul className="list-disc pl-4 space-y-1">
              <li><strong className="text-foreground">Strong PDE satisfaction within the implemented benchmark subspace:</strong> constant-stress affine fields satisfy ∇·σ(u) = 0 pointwise in Ω_e</li>
              <li><strong className="text-foreground">No interior interpolation:</strong> Field generated from boundary state w₀</li>
              <li><strong className="text-foreground">Boundary-only assembly:</strong> the meshed solver assembles through boundary integrals from a boundary reference state rather than interior interpolation</li>
              <li><strong className="text-foreground">Direct stress access:</strong> ∂_x u and ∂_y u available directly from w — no numerical differentiation</li>
            </ul>
            <p><strong className="text-foreground">Stress recovery:</strong></p>
            <MathBlock>ε(x,y) = ½(∇u + (∇u)ᵀ) = function of w(x,y)</MathBlock>
            <MathBlock>σ(x,y) = C : ε(x,y)</MathBlock>
            <p>Stress accuracy equals field accuracy (not one order lower, as in standard FEM).</p>
          </Section>

          <Section title="Magnus Convergence" sub="When the series converges absolutely">
            <MathBlock>∫₀ˢ ‖A(τ)‖ dτ {"<"} π</MathBlock>
            <p>For practical element sizes and material constants, this is easily satisfied. The series also converges for all s when the Lie algebra is nilpotent (closure), regardless of the norm bound.</p>
          </Section>
        </TabsContent>

        {/* Assembly */}
        <TabsContent value="assembly" className="mt-5 space-y-4">
          <Section title="Boundary Frame and DOFs" sub="Independent edge unknowns for inter-element coupling">
            <p>On each element edge e ⊂ ∂Ω_e, define a boundary displacement frame:</p>
            <MathBlock>û(s) = Σⱼ N_j(s) d̂_j   (1D shape functions N_j on the edge)</MathBlock>
            <p>Boundary DOFs d̂_j are shared between adjacent elements, ensuring C⁰ continuity of û across the mesh. The boundary state w₀ at the starting point γ(0) is constructed from û.</p>
          </Section>

          <Section title="Modified Hybrid Variational Functional" sub="Couples the Koen interior field to the boundary frame">
            <p>Following the classical hybrid-Trefftz approach, the two-field functional couples u_h (interior, from Koenian transport) to û (boundary frame):</p>
            <MathBlock>Π(u_h, û) = ∫_Ωe [½ε(u_h):C:ε(u_h) − f·u_h] dA − ∫_∂Ωe t(û)·(u_h − û) ds</MathBlock>
            <p><strong className="text-foreground">Stationarity conditions yield:</strong></p>
            <ol className="list-decimal pl-4 space-y-2">
              <li><strong className="text-foreground">Equilibrium in Ω_e:</strong> ∇·σ(u_h) = 0 — automatically satisfied (Magnus solution)</li>
              <li><strong className="text-foreground">Traction reciprocity on ∂Ω_e:</strong> σ(u_h)·n = function of û</li>
              <li><strong className="text-foreground">Weak boundary continuity:</strong> ∫_∂Ωe δû·[t(u_h) − t(û)] ds = 0</li>
            </ol>
          </Section>

          <Section title="Element Stiffness Matrix" sub="Boundary-only integrals via Dirichlet-to-Neumann operator">
            <p>Because u_h satisfies the PDE exactly, the element stiffness involves only boundary integrals:</p>
            <MathBlock>K_e = ∫_∂Ωe Nᵀ H N ds</MathBlock>
            <p>where N are boundary shape functions and H is the DtN kernel relating boundary displacements to boundary tractions. This is identical in structure to hybrid-Trefftz elements — the only difference is the source of the intra-element field (Magnus transport vs. analytic T-complete basis).</p>
            <p><strong className="text-foreground">Explicit construction:</strong></p>
            <ol className="list-decimal pl-4 space-y-1">
              <li>For each boundary trial function û_j, solve the interior transport equation with w₀^(j) corresponding to û_j on the boundary.</li>
              <li>Evaluate the interior field u_h^(j) = Π exp(Ω) w₀^(j).</li>
              <li>Compute traction t^(j) = σ(u_h^(j))·n on the boundary.</li>
              <li>Form K_ij = ∫_∂Ωe N_i t^(j) ds.</li>
            </ol>
          </Section>

          <Section title="Global Assembly and Solution" sub="Standard FEM assembly with boundary DOFs">
            <p>Element matrices K_e are assembled into the global system:</p>
            <MathBlock>K d̂ = F</MathBlock>
            <p>where d̂ collects all boundary DOFs and F includes external loads and prescribed boundary conditions. The global matrix K is symmetric and positive definite (conforming mesh, appropriate BCs). Interior fields are recovered by postprocessing:</p>
            <MathBlock>u_h(x,y) = Π exp(Ω(x,y)) w₀(d̂),   σ_h(x,y) = C : ε(u_h)</MathBlock>
          </Section>
        </TabsContent>

        {/* Kirsch */}
        <TabsContent value="kirsch" className="mt-5 space-y-4">
          <Section title="Kirsch (1898) Benchmark Problem" sub="Plate with circular hole under remote uniaxial tension">
            <p><strong className="text-foreground">Geometry:</strong> Rectangular plate 2L × 2W with central circular hole of radius a. For numerical tests: L/a = 5, W/a = 5 (finite plate approximation of infinite plate).</p>
            <p><strong className="text-foreground">Loading:</strong> Remote tension σ∞ in x-direction. Model quarter with symmetry BCs. Traction-free hole boundary.</p>
            <p><strong className="text-foreground">Analytical solution (Kirsch, 1898):</strong></p>
            <MathBlock>σ_rr(r,θ) = σ∞/2 · (1 − (a/r)²) + σ∞/2 · (1 − 4(a/r)² + 3(a/r)⁴) cos2θ</MathBlock>
            <MathBlock>σ_θθ(r,θ) = σ∞/2 · (1 + (a/r)²) − σ∞/2 · (1 + 3(a/r)⁴) cos2θ</MathBlock>
            <MathBlock>σ_rθ(r,θ) = −σ∞/2 · (1 + 2(a/r)² − 3(a/r)⁴) sin2θ</MathBlock>
            <p><strong className="text-foreground">At hole boundary (r = a):</strong></p>
            <MathBlock>σ_θθ(a, θ) = σ∞ · (1 − 2cos2θ)</MathBlock>
            <p><strong className="text-foreground">Maximum at θ = ±90°:</strong></p>
            <MathBlock>σ_max = 3σ∞,   K_t = σ_max / σ∞ = 3.0</MathBlock>
          </Section>

          <Section title="TK-FEM Validation Objectives" sub="Numerical comparison against Kirsch analytical solution">
            <ol className="list-decimal pl-4 space-y-2">
              <li><strong className="text-foreground">Stress field accuracy:</strong> Compute σ_xx, σ_yy, τ_xy using TK-FEM and conventional FEM. Compare against Kirsch using L² error norms.</li>
              <li><strong className="text-foreground">SCF extraction:</strong> Extract K_t from numerical solution at r=a, θ=90° and compare to 3.0.</li>
              <li><strong className="text-foreground">Convergence study:</strong> Plot error vs. number of elements for both methods. TK-FEM should achieve comparable accuracy with fewer elements due to exact interior fields.</li>
              <li><strong className="text-foreground">Magnus truncation study:</strong> Vary m_trunc (1..5) and assess impact on K_t accuracy. Determine minimum m needed for {"<5%"} error.</li>
            </ol>
          </Section>

          <Section title="References" sub="">
            <div className="space-y-2 text-xs text-muted-foreground font-mono">
              {[
                "[1] Hughes, T.J.R. (1987). The Finite Element Method. Prentice-Hall.",
                "[2] Zienkiewicz, O.C. et al. (1995). The Finite Element Method, 4th ed.",
                "[3] Jirousek, J. & Wroblewski, A. (1996). T-elements — State of the Art. CMAME.",
                "[4] Qin, Q.-H. (2000). The Trefftz Finite and Boundary Element Method.",
                "[5] Koen, C.J. (2025). Koenian Calculus: One-Shot Inversion via Transport Closure.",
                "[6] Koen, C.J. (2026). Koenian Structural Field Theory and Transport Closure.",
                "[7] Magnus, W. (1954). On the exponential solution of differential equations. CPAM.",
                "[8] Przemieniecki, J.S. (1968). Theory of Matrix Structural Analysis.",
                "[9] Iserles, A. et al. (2000). Lie-group methods. Acta Numerica.",
                "[10] Kirsch, E.G. (1898). Die Theorie der Elastizität. ZVDI.",
              ].map((ref, i) => (
                <div key={i} className="py-1 border-b border-border/30 last:border-0">{ref}</div>
              ))}
            </div>
          </Section>
        </TabsContent>
      </Tabs>
    </div>
  );
}
